### PR TITLE
New options and features

### PR DESCRIPTION
**Pull request by joaquincasares**
Thanks for the great work! I've been looking for something like this as I try to transition into Ubuntu from OSX! :)

Here a few fixes/improvements I made to the project:
* Add margins, usable screen area, and padding options.
* Renamed width,height to columns,rows to lessen confusion of new options.
* Ensure box selecting is limited to being > 0 and < width,height, respectively.
* Bind 'Escape' as a hotkey to hide a visible ration dialog.
* Add feature to auto-hide ration dialog after arranging windows, similar to Divvy. Currently defaulting to True.
* Improve CONFIG parsing code.

### CODE REVIEW

**Comment by Dinduks** [comment]
Hi Joaquin,
Any plans to merge this?

**Comment by joaquincasares** [comment]
Hey Samy,

I figured to wait for someone to test it besides me. :)

Would you mind trying my branch and ensuring it works well?

If so, I'll merge it into the main project's master branch.

Thanks!

**Comment by Dinduks** [comment]
I tried your branch as soon as I found the PR, and it looks good to me. :+1: I found it even more stable than onyxfish/ration.
That said, it's the first time I use ration so I might have missed something.

Btw, thank you @onyxfish for this awesome program. It'll sure make my migration to Linux easier. :beers:

**Comment by joaquincasares** [comment]
Sounds great. Thanks for the review! I've merged the branch.

+1 on @onyxfish making an awesome program. :)

**Pull request merged**
